apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: homey-app
  title: Tibber Homey App
  description: The Tibber app for Homey
  annotations:
    github.com/project-slug: tibber/com.tibber.athom
spec:
  type: app
  lifecycle: production
  consumesApis: [tibber-api-api]
